cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: 'public://favicon.ico'
  url: 'http://192.168.3.225/dcm2017/sites/default/files/favicon.ico'
  use_default: 0
schemas:
  bootstrap: 8000
  dcm2017: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://dcm-logo-new.png'
  url: ''
  use_default: 0
fluid_container: 0
table_responsive: '-1'
tooltip_enabled: 0
table: ''
