horizontal_menu: dcm2017
horizontal_depth: 3
off_canvas_menus: block-dcm2017-2
horizontal_wrapping_element: div
horizontal_breakpoint: wide
horizontal_media_query: null
include_css: true
off_canvas_position: left
off_canvas_theme: theme-black
horizontal_superfish: false
horizontal_superfish_delay: 300
horizontal_superfish_speed: 100
horizontal_superfish_speed_out: 100
horizontal_superfish_hoverintent: true
hammerjs: false
breakpoint_css_filepath: 'public://css'
_core:
  default_config_hash: DgAWl_7_B39CsIvJyK3vxn2mj8fNSQZSQyVRiTlGdrg
